"""Convert the konflux-ci/architecture Eleventy content tree into a Sourcey config.

Data-driven on purpose: the generated sourcey.config.ts mirrors the repository's own
published content tree exactly - no hand-curated page selection. Mapping (verified live):
  architecture/<path>.md  -> site /<path>/          (top-level 'architecture/' is stripped)
  ADR/<name>.md           -> site /ADR/<name>/
  architecture/index.md   -> site /                  (homepage)
Usage: python eleventy_nav_to_sourcey.py <repo_root> <out_config.ts>
"""
import json
import sys
from pathlib import Path

# AGENTS.md is a repo-internal agent index, never a published page.
SKIP = ("AGENTS.md",)
# ADR/ additionally skips what the repository's own lint scripts skip (see
# hack/lint-adr-numbers and hack/util/generate-adr-table): the ADR template, and
# the ADR index that `make build` generates - it may or may not exist in a given
# checkout, so skipping it keeps the output identical regardless of build state.
SKIP_ADR = SKIP + ("0000-adr-template.md", "index.md")


def slugs_for(repo: Path):
    groups = []

    def md_slugs(folder: Path, strip: str):
        skip = SKIP_ADR if folder.name == "ADR" else SKIP
        out = []
        for f in sorted(folder.glob("*.md")):
            if f.name in skip:
                continue
            rel = f.relative_to(repo).as_posix()[:-3]  # drop .md
            if rel.startswith(strip):
                rel = rel[len(strip):]
            out.append(rel)
        return out

    # Overview: architecture/index.md renders as the site homepage (slug "index")
    groups.append({"group": "Overview", "pages": ["index"]})
    groups.append({"group": "Core Services",
                   "pages": ["core/" + Path(p).name for p in
                             md_slugs(repo / "architecture" / "core", "architecture/core/")]})
    groups.append({"group": "Add-ons",
                   "pages": ["add-ons/" + Path(p).name for p in
                             md_slugs(repo / "architecture" / "add-ons", "architecture/add-ons/")]})
    groups.append({"group": "ADRs", "pages": md_slugs(repo / "ADR", "")})
    return groups


def main():
    repo = Path(sys.argv[1]).resolve()
    out = Path(sys.argv[2])
    groups = slugs_for(repo)
    total = sum(len(g["pages"]) for g in groups)
    config = (
        'import { defineConfig } from "sourcey";\n\n'
        "// GENERATED by eleventy_nav_to_sourcey.py from the repository's own content tree\n"
        "// (architecture/ + ADR/). The groups/pages below mirror the published site exactly -\n"
        "// no hand-picked selection. Mapping verified against live konflux-ci.dev URLs.\n"
        "export default defineConfig({\n"
        '  name: "Konflux Architecture",\n'
        '  repo: "https://github.com/konflux-ci/architecture",\n'
        '  siteUrl: "https://konflux-ci.dev",\n'
        '  baseUrl: "/architecture",\n'
        "  navigation: {\n"
        "    tabs: [{\n"
        + json.dumps({"tab": "Documentation", "slug": "", "groups": groups}, indent=6)[1:-1]
        + "\n    }]\n"
        "  }\n"
        "});\n"
    )
    out.write_text(config, encoding="utf-8", newline="\n")
    print(f"wrote {out} - {total} pages in {len(groups)} groups")


if __name__ == "__main__":
    main()
