import { defineConfig } from "sourcey";

// GENERATED by eleventy_nav_to_sourcey.py from the repository's own content tree
// (architecture/ + ADR/). The groups/pages below mirror the published site exactly -
// no hand-picked selection. Mapping verified against live konflux-ci.dev URLs.
export default defineConfig({
  name: "Konflux Architecture",
  repo: "https://github.com/konflux-ci/architecture",
  siteUrl: "https://konflux-ci.dev",
  baseUrl: "/architecture",
  navigation: {
    tabs: [{

      "tab": "Documentation",
      "slug": "",
      "groups": [
            {
                  "group": "Overview",
                  "pages": [
                        "index"
                  ]
            },
            {
                  "group": "Core Services",
                  "pages": [
                        "core/build-service",
                        "core/enterprise-contract",
                        "core/hybrid-application-service",
                        "core/index",
                        "core/integration-service",
                        "core/konflux-operator",
                        "core/konflux-ui",
                        "core/pipeline-service",
                        "core/release-service"
                  ]
            },
            {
                  "group": "Add-ons",
                  "pages": [
                        "add-ons/image-controller",
                        "add-ons/index",
                        "add-ons/internal-services",
                        "add-ons/kubearchive",
                        "add-ons/mintmaker",
                        "add-ons/multi-platform-controller",
                        "add-ons/project-controller",
                        "add-ons/pulp-access-controller"
                  ]
            },
            {
                  "group": "Architecture Decision Records",
                  "pages": [
                        "ADR/0000-adr-template",
                        "ADR/0001-pipeline-service-phase-1",
                        "ADR/0002-feature-flags",
                        "ADR/0003-interacting-with-internal-services",
                        "ADR/0004-component-image-location",
                        "ADR/0006-log-conventions",
                        "ADR/0007-change-management",
                        "ADR/0008-environment-provisioning",
                        "ADR/0009-pipeline-service-via-operator",
                        "ADR/0010-namespace-metadata",
                        "ADR/0011-roles-and-permissions",
                        "ADR/0012-namespace-name-format",
                        "ADR/0013-integration-service-api-contracts",
                        "ADR/0014-let-pipelines-proceed",
                        "ADR/0015-integration-service-two-phase-architecture",
                        "ADR/0016-integration-service-promotion-logic",
                        "ADR/0017-use-our-pipelines",
                        "ADR/0018-apps-continuous-perf-testing",
                        "ADR/0019-customize-url-github",
                        "ADR/0020-source-retention",
                        "ADR/0021-partner-tasks",
                        "ADR/0022-secret-mgmt-for-user-workloads",
                        "ADR/0023-git-references-to-furnish-integration-test-scenarios",
                        "ADR/0024-release-attribution",
                        "ADR/0025-appstudio-pipeline-serviceaccount",
                        "ADR/0026-specifying-ocp-targets-for-fbc",
                        "ADR/0027-container-images",
                        "ADR/0028-handling-snapshotenvironmentbinding-errors",
                        "ADR/0029-component-dependencies",
                        "ADR/0030-tekton-results-naming-convention",
                        "ADR/0031-sprayproxy",
                        "ADR/0032-decoupling-deployment",
                        "ADR/0033-enable-native-opentelemetry-tracing",
                        "ADR/0034-project-controller-for-multiversion",
                        "ADR/0035-apps-continuous-chaos-testing",
                        "ADR/0036-trusted-artifacts",
                        "ADR/0037-integration-service-promotes-to-GCL-immediately",
                        "ADR/0038-integration-service-composite-removal",
                        "ADR/0039-workspace-deprecation",
                        "ADR/0040-availability-probe-framework",
                        "ADR/0041-send-cloud-events",
                        "ADR/0042-provisioning-ephemeral-openshift-clusters",
                        "ADR/0044-spdx-support",
                        "ADR/0046-common-task-runner-image",
                        "ADR/0047-caching-for-container-build-layers",
                        "ADR/0048-movable-build-tests",
                        "ADR/0049-vsa-support",
                        "ADR/0050-exclude-events-api-from-user-rbac",
                        "ADR/0051-kite-poc-architecture-and-components",
                        "ADR/0052-gitops-onboarding-redesign",
                        "ADR/0053-trusted-task-model",
                        "ADR/0054-task-versioning",
                        "ADR/0055-slsa-source-provenance-verification",
                        "ADR/0056-revised-component-model",
                        "ADR/0057-pipeline-caching-feature-flag",
                        "ADR/0058-mintmaker-log-persistence",
                        "ADR/0059-backend-usage-telemetry-collection",
                        "ADR/0060-component-groups",
                        "ADR/0061-vcs-info-specification",
                        "ADR/0062-distributed-tracing",
                        "ADR/0063-generalized-build-release-pipelines",
                        "ADR/0064-hermeto-package-registry-proxy",
                        "ADR/0065-kubearchive",
                        "ADR/0066-ecosystem-native-distribution",
                        "ADR/0067-nudging-relationship-singleton-crd",
                        "ADR/0068-konflux-ci-dev-api-group",
                        "ADR/0069-reproducible-container-builds",
                        "ADR/0070-dual-compression-for-container-builds",
                        "ADR/0071-konflux-labels-annotations-finalizers"
                  ]
            }
      ]

    }]
  }
});
