baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Standalone Konflux Architecture Docs'
theme = ['github.com/konflux-ci/konflux-ci.github.io/website/themes/konflux', 'github.com/devcows/hugo-universal-theme']

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

# use relative links by default
relativeURLs = true

[params]
    mainSections = ["architecture", "decisions"]
    disabled_logo = false
    logo_text = "Konflux"
    date_format = "January 2, 2006"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"


[[menu.main]]
    name       = "Architecture"
    identifier = "menu.architecture"
    url        = "/architecture/"
    weight     = 3

[[menu.main]]
    name       = "Decisions"
    identifier = "menu.decisionss"
    url        = "/decisions/"
    weight     = 4

[[menu.main]]
    name       = "API"
    identifier = "menu.api"
    url        = "/ref/"
    weight     = 5
